[package]
name = "sirula-next-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
log = { version = "0.4.14", features = ["max_level_trace", "release_max_level_warn"] }
xdg = "2.4.0"
toml = "0.4.2"
serde = "1.0.136"