[Console]
binary = "/usr/bin/alacritty"
args = ["-e", "sh", "-c"]
icon-name = "Alacritty"

[UI]
anchor = [false, false, false, false]
margin = [0, 0, 0, 0]
width = 1300
height = 600
exclusive = false
icon-size = 64
lines = 2